name: Update Dependencies

on:
  schedule:
    # Run every Monday at 8:00 AM UTC
    - cron: "0 8 * * 1"
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv

      - name: Update Composer dependencies
        run: |
          composer update --no-interaction --prefer-dist
          composer normalize

      - name: Check for changes
        id: changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update composer dependencies"
          title: "🔄 Update Composer Dependencies"
          body: |
            This is an automated pull request to update Composer dependencies.

            Please review the changes before merging.

            - Updated composer.lock
            - Dependencies updated to latest compatible versions
          branch: update-dependencies
          delete-branch: true
